name: ph_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_audio: ^2.0.0
  audioplayers: ^6.1.0
  flutter_localizations:  # Thêm dòng này
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1


flutter:
  # Các assets (hình ảnh và âm thanh)
  assets:
    # Images
    - assets/images/yellowbird-midflap.png
    - assets/images/tuabin.png
    - assets/images/phitieu.png
    - assets/images/game.png
    - assets/images/bush.png
    - assets/images/house.png
    - assets/images/giphy.png
    - assets/images/pngtree-cute-penguin-ski-illustration-png-image_5472693.png
    - assets/images/pngtree-penguin-skiing-vector-png-image_12156156.png

    # Audio
    - assets/audio/game_over_deep_voice.mp3
    - assets/audio/clinking_coins.mp3
    - assets/audio/simple_whoosh.mp3
    - assets/audio/happy_adveture.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pngtree-penguin-skiing-vector-png-image_12156156.png"    # ← sửa đường dẫn thành đúng vị trí file
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/pngtree-penguin-skiing-vector-png-image_12156156.png"
    